### ISSUE TITLE
[feature] announcement through bot

### ISSUE THREAD

**Issue by chathu89916** [nylonee/hangupsbot#157] opened 2015-04-17 13:39 UTC
Add an announcement feature (for admins) to push an announcement through all the hangouts the bot is in. push to group hangouts/ personal hangouts.

**Comment by endofline** [comment] 2015-04-17 13:40
duplicate of #139

**Comment by endofline** [comment] 2015-04-20 10:55
closing this in favor of the duplicate

**Closed by endofline** 2015-04-20 10:55 UTC
Labels: duplicate
